FROM golang:1.8
MAINTAINER Benjamin Borbe <bborbe@rocketnews.de>
ARG VERSION
COPY Makefile /
COPY sources /go/src/github.com/bborbe/postgres_backup_cron
WORKDIR /
RUN make setup
RUN make buildgo
CMD ["/bin/bash"]
